# Generated by Django 2.2.1 on 2019-06-01 09:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FSABSReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FSAPLReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Input',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization', models.CharField(max_length=50)),
                ('project', models.CharField(max_length=50, unique=True)),
                ('valuation_date', models.DateField(blank=True, null=True)),
                ('statutory_corporate_tax_rate', models.FloatField()),
                ('statutory_mat_rate', models.FloatField(blank=True, null=True)),
                ('post_tax_wacc', models.FloatField()),
                ('long_term_growth_rate', models.FloatField()),
                ('company_specific_risk', models.FloatField(blank=True, null=True)),
                ('contingent_liability', models.FloatField(blank=True, null=True)),
                ('total_shares_outstanding', models.FloatField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WACCParticulars',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('particulars', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='YOYGrowth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report', models.CharField(default='Sales', max_length=50)),
                ('year_neg_1', models.FloatField()),
                ('year_0', models.FloatField()),
                ('year_pos_1', models.FloatField()),
                ('year_pos_2', models.FloatField()),
                ('year_pos_3', models.FloatField()),
                ('year_pos_4', models.FloatField()),
                ('year_pos_5', models.FloatField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inputApp.Input')),
            ],
        ),
        migrations.CreateModel(
            name='WACC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('particulars', models.CharField(max_length=50)),
                ('percentage', models.FloatField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inputApp.Input')),
            ],
        ),
        migrations.CreateModel(
            name='FSAPL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report', models.CharField(max_length=50)),
                ('year_neg_2', models.FloatField(verbose_name='Year -2')),
                ('year_neg_1', models.FloatField(verbose_name='Year -1')),
                ('year_0', models.FloatField(verbose_name='Year 0')),
                ('year_pos_1', models.FloatField(verbose_name='Year 1')),
                ('year_pos_2', models.FloatField(verbose_name='Year 2')),
                ('year_pos_3', models.FloatField(verbose_name='Year 3')),
                ('year_pos_4', models.FloatField(verbose_name='Year 4')),
                ('year_pos_5', models.FloatField(verbose_name='Year 5')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inputApp.Input')),
            ],
        ),
        migrations.CreateModel(
            name='FSABS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report', models.CharField(max_length=50)),
                ('year_0', models.FloatField(verbose_name='Year 0')),
                ('year_pos_1', models.FloatField(verbose_name='Year 1')),
                ('year_pos_2', models.FloatField(verbose_name='Year 2')),
                ('year_pos_3', models.FloatField(verbose_name='Year 3')),
                ('year_pos_4', models.FloatField(verbose_name='Year 4')),
                ('year_pos_5', models.FloatField(verbose_name='Year 5')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inputApp.Input')),
            ],
        ),
        migrations.CreateModel(
            name='DCF',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report', models.CharField(max_length=50)),
                ('year_1', models.FloatField()),
                ('year_2', models.FloatField()),
                ('year_3', models.FloatField()),
                ('year_4', models.FloatField()),
                ('year_5', models.FloatField()),
                ('terminal_period', models.FloatField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inputApp.Input')),
            ],
        ),
    ]
