# Generated by Django 2.2.1 on 2019-06-02 06:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inputApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Output',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('long_term_sustainable_growth_rate', models.FloatField()),
                ('terminal_value', models.FloatField()),
                ('sum_of_present_value_of_net_free_cash_flows_to_equity', models.FloatField()),
                ('present_value_of_terminal_value', models.FloatField()),
                ('gross_equity_value', models.FloatField()),
                ('investments', models.FloatField()),
                ('cash_and_equivalent', models.FloatField()),
                ('other_non_current_assets', models.FloatField()),
                ('pref_shares', models.FloatField()),
                ('debt', models.FloatField()),
                ('contingent_liabilities', models.FloatField()),
                ('equity_value', models.FloatField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inputApp.Input')),
            ],
        ),
    ]
