# Generated by Django 2.2.1 on 2019-06-03 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inputApp', '0002_output'),
    ]

    operations = [
        migrations.AlterField(
            model_name='input',
            name='project',
            field=models.CharField(max_length=50),
        ),
    ]
