# Generated by Django 2.2.1 on 2019-06-05 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inputApp', '0003_auto_20190603_1356'),
    ]

    operations = [
        migrations.AddField(
            model_name='dcf',
            name='wacc',
            field=models.ManyToManyField(blank=True, null=True, to='inputApp.WACC'),
        ),
    ]
