# Generated by Django 2.2.1 on 2019-06-05 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inputApp', '0004_dcf_wacc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dcf',
            name='wacc',
            field=models.ManyToManyField(to='inputApp.WACC'),
        ),
    ]
