# Generated by Django 2.2.1 on 2019-06-05 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inputApp', '0005_auto_20190605_1341'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dcf',
            name='wacc',
        ),
        migrations.AddField(
            model_name='dcf',
            name='wacc_rel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inputApp.WACC'),
        ),
    ]
