# Generated by Django 2.2.1 on 2019-06-05 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inputApp', '0006_auto_20190605_1351'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dcf',
            name='wacc_rel',
        ),
    ]
